### ISSUE TITLE
Tool Broken in DCS 2.5.6

### ISSUE THREAD

**Issue by jspencer46** [Santi871/DCSWaypointEditor#32]
DCS Update to 2.5.6 has broken your very useful tool. Hope you can fix it.

**Comment by isotaan** [comment]
Getting "unable to capture" error:

2020-03-08 12:46:35,926:gui: DEBUG - Attempting to capture map coords
2020-03-08 12:46:36,180:gui: ERROR - Failed to parse captured text
Traceback (most recent call last):
  File "src\gui.py", line 564, in input_parsed_coords
    position, elevation = self.parse_map_coords_string(captured_coords)
  File "src\gui.py", line 540, in parse_map_coords_string
    decoded_mgrs = mgrs.UTMtoLL(mgrs.decode(mgrs_string))
  File "src\pymgrs.py", line 360, in decode
    raise ("MGRSPoint coverting from nothing")
TypeError: exceptions must derive from BaseException

**Comment by rhulsker** [comment]
I have submitted a fix (i hope) for this issue. While we are waiting for the pull request to be accepted I have published a new release out of my repository for testing. You can find it here.

https://github.com/rhulsker/DCSWaypointEditor/releases

Please let me know if this works for you.

**Comment by PVI-Bat** [comment]
With the v0.9.9b3-testing version of rhulsker released on 3 May 2020 it is possible to capture; but there are no more preset locations and I can't find how to export the created profiles.

**Comment by EpiicPenguin** [comment]
Make sure you don't have any overlays in the top left corner of the screen when the f10 map is up. I had steam FPS overlay up and and it covered the word MAP and it kept failing Capture.
turned off the FPS overlay and it worked.
