### ISSUE TITLE
Running DCS open beta - Unable to Capture F10 Waypoint - Capture failure Error

### ISSUE THREAD

**Issue by falcon76** [Santi871/DCSWaypointEditor#34]
I just tried to install this tool but I am unable to capture waypoints from the F10 Map.

installed the ocr software no errors
installed the bios no errors 
using two monitor setup with 4k 
open mission editor | click Alt Y - (Ndd - mm - ss.ss Edd - mm - ss.ss format )
click ctl+shft+t - capture turns on 
Hover over spot on map | click spot just to make sure it is in the right spot 
click ctl+t 
Failure to capture coordinate error appears.

Anything that I am doing wrong?  I have not tried to Import anything yet.
Thanks Falcon

**Comment by MichaelHatz** [comment]
Can confirm that this is occuring for me too, would love for this to get fixed as it's such a handy tool. If it helps I am also using two monitors with a resolution of 1080p, and correct format for position in DCS but still I receive **Status: Failed to capture**

**Log:**

Program version: v0.9.9b2

2020-04-28 00:19:15,463:db: DEBUG - Connected to database
2020-04-28 00:19:15,470:gui: INFO - Tesseract path is: C:\Program Files\Tesseract-OCR\tesseract.exe
2020-04-28 00:19:15,571:gui: INFO - Tesseract version is: 5.0.0-alpha.20200328
2020-04-28 00:19:15,571:gui: DEBUG - Creating GUI
2020-04-28 00:19:16,984:gui: DEBUG - Event: capture
2020-04-28 00:19:16,984:gui: DEBUG - Values: {'profileSelector': '', 'activesList': [], 0: None, 'baseSelector': '', 'msnName': '', 'WP': True, 'MSN': False, 'FP': False, 'ST': False, 'IP': False, 'DP': False, 'HA': False, 'HB': False, 'sequence': 'None', 'latDeg': '', 'latMin': '', 'latSec': '', 'lonDeg': '', 'lonMin': '', 'lonSec': '', 'elevFeet': '', 'elevMeters': '', 'mgrs': '', 'hornet': True, 'harrier': False, 'mirage': False, 'tomcat': False, 'warthog': False}
2020-04-28 00:19:17,871:gui: DEBUG - Event: Add
2020-04-28 00:19:17,871:gui: DEBUG - Values: {'profileSelector': '', 'activesList': [], 0: None, 'baseSelector': '', 'msnName': '', 'WP': True, 'MSN': False, 'FP': False, 'ST': False, 'IP': False, 'DP': False, 'HA': False, 'HB': False, 'sequence': 'None', 'latDeg': '', 'latMin': '', 'latSec': '', 'lonDeg': '', 'lonMin': '', 'lonSec': '', 'elevFeet': '', 'elevMeters': '', 'mgrs': '', 'hornet': True, 'harrier': False, 'mirage': False, 'tomcat': False, 'warthog': False}
2020-04-28 00:19:17,871:gui: ERROR - Failed to validate coords: could not convert string to float: 
2020-04-28 00:19:21,942:gui: DEBUG - Attempting to capture map coords
2020-04-28 00:19:22,273:gui: ERROR - Failed to parse captured text
Traceback (most recent call last):
  File "src\gui.py", line 564, in input_parsed_coords
    position, elevation = self.parse_map_coords_string(captured_coords)
  File "src\gui.py", line 536, in parse_map_coords_string
    lat_string, lon_string, format_str="d%-%m%-%S")
  File "site-packages\LatLon23\__init__.py", line 559, in string2latlon
  File "site-packages\LatLon23\__init__.py", line 334, in string2geocoord
  File "site-packages\LatLon23\__init__.py", line 63, in set_degree
ValueError: could not convert string to float: '|'
2020-04-28 00:19:28,251:gui: DEBUG - Event: capture
2020-04-28 00:19:28,251:gui: DEBUG - Values: {'profileSelector': '', 'activesList': [], 0: None, 'baseSelector': '', 'msnName': '', 'WP': True, 'MSN': False, 'FP': False, 'ST': False, 'IP': False, 'DP': False, 'HA': False, 'HB': False, 'sequence': 'None', 'latDeg': '', 'latMin': '', 'latSec': '', 'lonDeg': '', 'lonMin': '', 'lonSec': '', 'elevFeet': '', 'elevMeters': '', 'mgrs': '', 'hornet': True, 'harrier': False, 'mirage': False, 'tomcat': False, 'warthog': False}
2020-04-28 00:19:34,239:gui: DEBUG - Attempting to capture map coords
2020-04-28 00:19:34,495:gui: ERROR - Failed to parse captured text
Traceback (most recent call last):
  File "src\gui.py", line 564, in input_parsed_coords
    position, elevation = self.parse_map_coords_string(captured_coords)
  File "src\gui.py", line 540, in parse_map_coords_string
    decoded_mgrs = mgrs.UTMtoLL(mgrs.decode(mgrs_string))
  File "src\pymgrs.py", line 360, in decode
    raise ("MGRSPoint coverting from nothing")
TypeError: exceptions must derive from BaseException
2020-04-28 00:19:36,816:gui: DEBUG - Event: mgrs
2020-04-28 00:19:36,816:gui: DEBUG - Values: {'profileSelector': '', 'activesList': [], 0: None, 'baseSelector': '', 'msnName': '', 'WP': True, 'MSN': False, 'FP': False, 'ST': False, 'IP': False, 'DP': False, 'HA': False, 'HB': False, 'sequence': 'None', 'latDeg': '', 'latMin': '', 'latSec': '', 'lonDeg': '', 'lonMin': '', 'lonSec': '', 'elevFeet': '', 'elevMeters': '', 'mgrs': '', 'hornet': True, 'harrier': False, 'mirage': False, 'tomcat': False, 'warthog': False}

**Comment by falcon76** [comment]
I get the same error in my log file

**Comment by rhulsker** [comment]
I have submitted a fix (i hope) for this issue.  While we are waiting for the pull request to be accepted I have published a new release out of my repository for testing.  You can find it here.

https://github.com/rhulsker/DCSWaypointEditor/releases

Please let me know if this works for you.

**Comment by sobe1205** [comment]
rhulsker <notifications@github.com>
Sun, May 3, 7:25 PM (12 hours ago)
to Comment, Santi871/DCSWaypointEditor, me
Check that your dcs-waypoint-editor directory has the files "map.bin" and "arrow.bin" ( I uploaded the wrong zip file at one point which was missing these files, if you don't have them you should re-download it)
YESTERDAYS DOWNLOAD DID NOT HAVE THEM.  RE-DOWNLOADED TODAY AND GOT THEM. 
Edit your settings.ini and add or edit the following line
save_debug_images = true
grace_period = 5
button_release_short_delay = 0.2
button_release_medium_delay = 0.5
tesseract_path = E:\Program Files\Tesseract-OCR\tesseract.exe
dcs_path = C:\Users\13057\Saved Games\DCS.openbeta\
db_name = profiles_new.db
capture_key = ctrl+alt+p
quick_capture_hotkey = ctrl+alt+o
enter_aircraft_hotkey = ctrl+alt+i
log_raw_tesseract_output = false
save_debug_images = true
I AM RUNNING THE PROGRAM AS AN ADMIN
RUNNING HELIOS ON 3 SCREENS.  1 IS THE GAME, 2 IS THE HELIOS COCKPIT AND 3 IS FOR UTILITIES SUCH AS TEAMSPEACK, SRS, ETC.   THE ONLY TESTING THAT I DID WAS WITHOUT HELIOS AND ONLY FOR THE MANUAL ENTRY METHOD.  NEVER GOT TO THE F10 METHOD.  
NO JOY. 
This will cause it to save the screenshots and crops it is using each time. When you capture coordinates it will create a directory like "2020-05-03-20-19-33" (year, month, day, hour, min, sec). In this directory it will save each of the screenshots, and the crops it makes to send to tesseract if it gets that far.
I AM ATTACHING THE LOG.  I COULD NOT LOCATE ANY DIRECTORIES LIKE YOU DESCRIBE IN THE FOLDER.  COULD THEY BE SOMEHERE ELSE?
Try it again, look at the images in that directory to make sure they don't contain any private information and upload them here along with the logfile. I am primarily interested in the screenshot of the screen that has the DCS map window open, but the more information the better.
[log.txt](https://github.com/Santi871/DCSWaypointEditor/files/4576427/log.txt)

**Comment by falcon76** [comment]
looks like the latest version is working.  
thanks 
Falcon

**Comment by sobe1205** [comment]
falcon76
I have tried to get this program to work without any luck.  Perhaps you could provide how you did it?
sobe

**Comment by rhulsker** [comment]
Im not sure what you mean, are you talking about working with the source?

**Comment by falcon76** [comment]
Sobe1205 
  I was able to get it working by:
1. downloading the version in this thread 
2. changing the INI Setting "Save_Debug_Images = true"
3. Run as admin
4. Started dcs ME, placed a plane on the runway
5. Started the mission and joined the plane
6. clicked on the F10 Map 
7. clicked Alt Y until it displayed MGRS (you need this coodinate or the dms format)
8. shft+ctl+t
9. found a point on the map, clicked ctrl + t
10. coordinates populated and set name and sequence and then Add button.

**Comment by sobe1205** [comment]
Which plane r u using

**Comment by falcon76** [comment]
F18

**Comment by sobe1205** [comment]
falcon76
You are better than me.  I am giving up.  While I use 2 screens, I tried it with just one screen and the F18 and could not get it to work.

**Comment by JohnyJack01** [comment]
I have the exact same issue. Tried every suggestion I found here (running as admin, having arrow.bin and map.bin, tried with different releases - still the same). I am using just one Screen and was unable to make it work.

Here is the log:

```
Program version: v0.9.9b2

2020-09-30 23:42:01,437:db: DEBUG - Connected to database
2020-09-30 23:42:01,445:gui: INFO - Tesseract path is: D:/SW/Tesaract/tesseract.exe
2020-09-30 23:42:01,805:gui: INFO - Tesseract version is: 5.0.0-alpha.20200328
2020-09-30 23:42:01,805:gui: DEBUG - Creating GUI
2020-09-30 23:42:08,701:gui: DEBUG - Event: mgrs
2020-09-30 23:42:08,701:gui: DEBUG - Values: {'profileSelector': '', 'activesList': [], 0: None, 'baseSelector': '', 'msnName': '', 'WP': True, 'MSN': False, 'FP': False, 'ST': False, 'IP': False, 'DP': False, 'HA': False, 'HB': False, 'sequence': 'None', 'latDeg': '', 'latMin': '', 'latSec': '', 'lonDeg': '', 'lonMin': '', 'lonSec': '', 'elevFeet': '', 'elevMeters': '', 'mgrs': '', 'hornet': True, 'harrier': False, 'mirage': False, 'tomcat': False, 'warthog': False}
2020-09-30 23:42:08,812:gui: DEBUG - Event: mgrs
2020-09-30 23:42:08,812:gui: DEBUG - Values: {'profileSelector': '', 'activesList': [], 0: None, 'baseSelector': '', 'msnName': '', 'WP': True, 'MSN': False, 'FP': False, 'ST': False, 'IP': False, 'DP': False, 'HA': False, 'HB': False, 'sequence': 'None', 'latDeg': '', 'latMin': '', 'latSec': '', 'lonDeg': '', 'lonMin': '', 'lonSec': '', 'elevFeet': '', 'elevMeters': '', 'mgrs': '', 'hornet': True, 'harrier': False, 'mirage': False, 'tomcat': False, 'warthog': False}
2020-09-30 23:42:09,204:gui: DEBUG - Event: mgrs
2020-09-30 23:42:09,205:gui: DEBUG - Values: {'profileSelector': '', 'activesList': [], 0: None, 'baseSelector': '', 'msnName': '', 'WP': True, 'MSN': False, 'FP': False, 'ST': False, 'IP': False, 'DP': False, 'HA': False, 'HB': False, 'sequence': 'None', 'latDeg': '', 'latMin': '', 'latSec': '', 'lonDeg': '', 'lonMin': '', 'lonSec': '', 'elevFeet': '', 'elevMeters': '', 'mgrs': '', 'hornet': True, 'harrier': False, 'mirage': False, 'tomcat': False, 'warthog': False}
2020-09-30 23:42:21,876:gui: DEBUG - Attempting to capture map coords
2020-09-30 23:42:22,325:gui: ERROR - Failed to parse captured text
Traceback (most recent call last):
  File "src\gui.py", line 564, in input_parsed_coords
    position, elevation = self.parse_map_coords_string(captured_coords)
  File "src\gui.py", line 536, in parse_map_coords_string
    lat_string, lon_string, format_str="d%-%m%-%S")
  File "site-packages\LatLon23\__init__.py", line 559, in string2latlon
  File "site-packages\LatLon23\__init__.py", line 334, in string2geocoord
  File "site-packages\LatLon23\__init__.py", line 63, in set_degree
ValueError: could not convert string to float: '|'
2020-09-30 23:42:37,654:gui: DEBUG - Event: None
2020-09-30 23:42:37,655:gui: DEBUG - Values: None
2020-09-30 23:42:37,655:gui: INFO - Exiting...
2020-09-30 23:42:37,657:root: INFO - Finished
```

**Comment by JohnyJack01** [comment]
After some playing around I was able to make it work. I had to do 3 steps:
1. Download latest pre-release version: Program version v1.0.0b1 (Does not work with 0.9.9 versions for me)
2. Switch DCS to English language instead of my native (Czech): put "EN" into <DCS_installation_folder>/config/lang.cfg
3. Turn-off Steam ingame FPS pointer in left upper corner 

All three steps has to be fullfilled and then it stars to work (at least for me)!

**Comment by falcon76** [comment]
Thanks for the heads up.

**Comment by EpiicPenguin** [comment]
Make sure you don't have any overlays in the top left corner of the screen when the f10 map is up. I had steam FPS overlay up and and it covered the word MAP and it kept failing Capture.
turned off the FPS overlay and it worked.
