### ISSUE TITLE
DCS Open Beta F-18 - Failed to Capture

### ISSUE THREAD

**Issue by Dancer2124** [Santi871/DCSWaypointEditor#48]
Continuing to get errors like this on multiple versions of the waypoint editor: 

[PREFERENCES]
grace_period = 5
button_release_short_delay = 0.2
button_release_medium_delay = 0.5
tesseract_path = D:/Data/Applications/Tesseract/tesseract.exe
dcs_path = C:/Users/Graig/Saved Games/DCS.openbeta/
db_name = profiles_new.db
capture_key = 1
quick_capture_hotkey = ctrl+shift+t
enter_aircraft_hotkey = 
log_raw_tesseract_output = false
save_debug_images = false

--------------------

Program version: v0.9.9b2

2021-01-25 13:08:14,856:db: DEBUG - Connected to database
2021-01-25 13:08:14,867:gui: INFO - Tesseract path is: D:/Data/Applications/Tesseract/tesseract.exe
2021-01-25 13:08:15,986:gui: INFO - Tesseract version is: 5.0.0-alpha.20201127
2021-01-25 13:08:15,986:gui: DEBUG - Creating GUI
2021-01-25 13:08:19,741:gui: DEBUG - Event: capture
2021-01-25 13:08:19,742:gui: DEBUG - Values: {'profileSelector': '', 'activesList': [], 0: None, 'baseSelector': '', 'msnName': '', 'WP': True, 'MSN': False, 'FP': False, 'ST': False, 'IP': False, 'DP': False, 'HA': False, 'HB': False, 'sequence': 'None', 'latDeg': '', 'latMin': '', 'latSec': '', 'lonDeg': '', 'lonMin': '', 'lonSec': '', 'elevFeet': '', 'elevMeters': '', 'mgrs': '', 'hornet': True, 'harrier': False, 'mirage': False, 'tomcat': False, 'warthog': False}
2021-01-25 13:08:21,936:gui: DEBUG - Attempting to capture map coords
2021-01-25 13:08:22,247:gui: DEBUG - Looking for map on screen 1
2021-01-25 13:08:22,512:gui: DEBUG - Minval: -0.4580914080142975 Maxval: 0.5928191542625427 Minloc: (1425, 958) Maxloc: (12, 0)
2021-01-25 13:08:22,512:gui: DEBUG - Raise exception (could not find the map anywhere i guess)
2021-01-25 13:08:22,512:gui: ERROR - Failed to parse captured text
Traceback (most recent call last):
  File "src\gui.py", line 657, in input_parsed_coords
  File "src\gui.py", line 546, in capture_map_coords
ValueError: F10 map not found

- I am using DD,MM,SS.SS
- I have updated and reinstalled DCS BIOS and the waypoint editor
- I have repaired DCS

Any insight on the issue and possible fixes would be much appreciated.

**Comment by jspencer46** [comment]
See Issue #32 for fix.

**Comment by EpiicPenguin** [comment]
Make sure you don't have any overlays in the top left corner of the screen when the f10 map is up. I had steam FPS overlay up and and it covered the word MAP and it kept failing Capture.
turned off the FPS overlay and it worked.
