### ISSUE TITLE
German Language not supportet

### ISSUE THREAD

**Issue by neorm** [Santi871/DCSWaypointEditor#5]
Hi,

it would be nice if you could support the German Language
![Screen_190610_114954](https://user-images.githubusercontent.com/9902367/59188134-449cb300-8b77-11e9-9161-5868ebf04b28.png)

Log:
2019-06-10 11:48:02,353:gui: DEBUG - Attempting to capture map coords
2019-06-10 11:48:02,671:gui: ERROR - Failed to parse captured text
Traceback (most recent call last):
  File "src\gui.py", line 404, in input_parsed_coords
    position, elevation = self.parse_map_coords_string(captured_coords)
  File "src\gui.py", line 395, in parse_map_coords_string
    raise ValueError("Unable to parse elevation: " + elevation)
ValueError: Unable to parse elevation: 343FuB
2019-06-10 11:48:10,586:gui: DEBUG - Event: mgrs
2019-06-10 11:48:10,586:gui: DEBUG - Values: {'profileSelector': '', 'activesList': [], 'baseSelector': '', 'msnName': '', 'WP': True, 'MSN': False, 0: False, 1: False, 2: False, 3: False, 4: False, 'sequence': 'None', 'latDeg': '', 'latMin': '', 'latSec': '', 'lonDeg': '', 'lonMin': '', 'lonSec': '', 'elevFeet': '', 'elevMeters': '', 'mgrs': '', 5: True, 6: False, 7: False, 8: False, 9: False}
2019-06-10 11:48:10,586:gui: ERROR - Failed to decode MGRS: exceptions must derive from BaseException

**Comment by neorm** [comment]
Just Support "FuB" as feet

**Comment by neorm** [comment]
I changed to the English language
